set location=d:\testserver
set cobp=%location%\SOURCE\SRCMANG\NDP\PROD\COBP
set cobn=%location%\SOURCE\SRCMANG\NDP\PROD\COBN

set copymf=%COBCPY%

set MFE_batch=?.prj
mfecl /addfile %MFE_BATCH% %SOURCE%\BDBCL870.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS362.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS462.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS464.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS701.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS702.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS703.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS704.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS750.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS753.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS893.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCLS894.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCRV180.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCRV983.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCRV984.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCRV985.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDCRV987.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDHUN750.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDPHD007.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\BDSLV997.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDAUD020.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDAUD210.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDAUD750.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDAUD821.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDAUD850.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDAUD951.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBCL639.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBCL886.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBCL887.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBCL899.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBCL978.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBCL990.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBCL991.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBCL992.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBCL993.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN501.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN502.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN504.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN511.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN512.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN521.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN522.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN526.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN532.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN534.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN536.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN537.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN543.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN555.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN564.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN565.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN569.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN570.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN572.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN573.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN577.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN582.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN720.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN840.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN841.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN842.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN843.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN862.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN867.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN873.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN894.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN895.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBIN896.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBON551.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDBON847.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS030.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS031.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS032.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS092.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS401.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS404.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS405.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS410.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS473.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS776.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS801.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS805.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS806.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS807.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS815.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS816.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS817.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCLS992.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM005.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM500.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM501.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM502.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM503.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM504.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM506.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM507.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM508.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM509.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM510.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM511.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM513.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCOM550.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCRE050.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCRE301.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCRV807.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTCAB3.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTCPCV.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC015.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC018.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC019.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC020.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC021.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC022.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC023.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC024.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC025.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC027.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC028.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC030.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC105.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC106.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC108.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC145.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC147.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC148.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC149.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC154.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC203.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC250.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC267.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC300.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC303.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC305.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC370.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC371.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC372.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC373.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC374.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC375.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC376.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC377.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC378.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC379.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC380.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC381.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC603.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC619.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC641.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC642.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC643.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC645.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC647.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC648.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC649.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC652.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC656.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC657.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC948.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC949.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC950.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC951.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC952.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC956.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC957.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC958.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC959.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC961.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC962.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC963.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC964.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC965.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC966.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC967.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC968.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC969.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC973.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC974.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC978.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCTC980.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCUS600.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCUS610.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCUS660.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN001.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN002.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN003.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN010.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN015.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN020.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN030.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN040.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN042.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN045.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN055.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN070.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN101.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN105.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN110.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN201.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN205.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN210.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN310.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN315.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN318.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN320.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN325.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN330.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN335.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN340.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN345.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN350.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN355.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN360.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN410.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN420.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN515.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN520.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN522.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN525.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN526.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN527.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN528.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN529.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN530.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN534.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN535.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN550.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN555.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN558.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN610.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN705.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN710.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN740.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN781.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN793.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN797.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN805.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN810.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN840.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN847.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN881.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN893.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN897.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN900.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN901.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN902.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN905.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN908.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN909.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN911.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN912.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN913.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN914.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN915.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN916.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN920.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN923.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN926.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN927.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN928.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN930.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN931.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN932.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN933.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN934.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN935.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN940.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN942.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN943.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN944.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN945.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN947.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN948.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN949.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN950.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN960.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN961.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN962.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN963.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN964.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN965.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN966.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN967.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN968.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDCVN981.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDDJR800.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDDRB003.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS400.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS401.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS402.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS403.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS404.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS412.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS413.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS415.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS416.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS417.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS418.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS450.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDIRS499.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDLIF333.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMAS400.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMAS401.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMEM126.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMEM795.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMKG806.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMKG807.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMONTBU.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMON002.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMON160.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMON970.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDMON991.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS320.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS480.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS483.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS486.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS487.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS577.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS680.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS741.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS79A.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS841.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS910.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS911.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDORS990.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDPJO680.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDPJO695.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDPJO697.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDSCY500.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDSCY502.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDSCY504.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDSCY506.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDSCY508.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDSCY510.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDSCY512.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\MDSLV900.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\XXXPDXX.cbl

mfecl /addfile %MFE_BATCH% %SOURCE%\XXXSORC.cbl

